origin_hostname               = "lalexand-amd-terra-prod.akamaized.net"
cp_code                       = 1698638
property_name                 = "lalexand-amd-terra_prod"
contract_id                   = "ctr_C-1ED34DY"
group_id                      = "grp_63802"
hostname                      = "lalexand-amd-terra-prod.akamaized.net"
edge_hostname                 = "lalexand-amd-terra-prod.akamaized.net"
env                           = "prod"
property_version_notes        = "Terraform update for prod environment - Aug 31 change Update 7"
activate_latest_on_staging    = false
activate_latest_on_production = false